name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        working-directory: MyProject
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests using pytest
        working-directory: MyProject
        id: unit-tests
        run: pytest
        continue-on-error: true

  deploy:
      name: Deploy to Test Environment
      needs: build
      if: ${{ needs.build.result == 'success' }}
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.x

        - name: Deploy to test environment
          run: |
            # Add your deployment steps here
            echo "Deploying to test environment..."